# Generated by Django 2.2.4 on 2021-03-03 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('title', models.CharField(max_length=100)),
                ('rating', models.CharField(max_length=10)),
                ('genra', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=1000)),
                ('duration', models.CharField(max_length=100)),
                ('leading_actor', models.CharField(max_length=100)),
                ('supporting_actor', models.CharField(max_length=100)),
                ('director', models.CharField(max_length=200)),
                ('release_date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movies_created', to='login_app.User')),
            ],
        ),
    ]
