# Generated by Django 2.2.4 on 2021-03-12 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='duration',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='movie',
            name='supporting_actor',
            field=models.CharField(max_length=200),
        ),
    ]
