# Generated by Django 2.2.4 on 2021-03-15 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0002_auto_20210312_1310'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='genra',
            new_name='genre',
        ),
    ]
